### ISSUE TITLE
python-plaso is outdated (encoding issue)

### ISSUE THREAD

**Issue by 2xyo** [sans-dfir/sift-bootstrap#18]
Hi,

The packaged version of `log2timeline.py` has an encoding issue :
````
$ log2timeline.py
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 438, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 407, in Main
    arg_parser.print_help()
  File "/usr/lib/python2.7/argparse.py", line 2329, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python2.7/argparse.py", line 2343, in _print_message
    file.write(message)


$ log2timeline.py -h
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 438, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 376, in Main
    options = arg_parser.parse_args()
  File "/usr/lib/python2.7/argparse.py", line 1690, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1722, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1928, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python2.7/argparse.py", line 1868, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python2.7/argparse.py", line 1796, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python2.7/argparse.py", line 996, in __call__
    parser.print_help()
  File "/usr/lib/python2.7/argparse.py", line 2329, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python2.7/argparse.py", line 2343, in _print_message
    file.write(message)

````

The issue is the missing `u` for unicode at : `/usr/bin/log2timeline.py:176`
````
  description = (
      """
      log2timeline is the main front-end to the plaso back-end, used to
      collect and correlate events extracted from a filesystem.

      More information can be gathered from here:
        http://plaso.kiddaland.net/usage/log2timeline
      """)
```

This bug is not present in the [official repository](https://github.com/log2timeline/plaso/blob/43ab2ad9ba04597e9f3c4e0c64c0a49d965e7836/plaso/frontend/log2timeline.py#L176) thanks to [this commit](https://github.com/log2timeline/plaso/commit/4ee703bc1c4bdfeccfdfa21f94eb38dec770b4af#diff-bc544efabc3d7513932e9d6762fe01feL176). 
Versions
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

$ log2timeline.py -v
log2timeline - plaso back-end 1.1.1_20141103

```
plaso version
```
/var/cache/apt/archives/python-plaso_1.1.1-dev-20141103-1ubuntu1_amd64.deb

```

**Comment by ekristen** [comment]
v1.2.0 is in now.
